[package]
name = "tokio-postgres-rustls"
description = "Rustls integration for tokio-postgres"
version = "0.6.0"
authors = ["Jasper <jasper@jasperhugo.com>"]
repository = "https://github.com/jbg/tokio-postgres-rustls"
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
bytes = "0.6"
futures = "0.3"
ring = "0.16"
rustls = "0.19"
tokio = "0.3"
tokio-postgres = "0.6"
tokio-rustls = "0.21"
webpki = "0.21"

[dev-dependencies]
env_logger = { version = "0.8", default-features = false }
tokio = { version = "0.3", features = ["macros", "rt"] }
